DELETE http://localhost:3003/api/blogs/68f7b0af83b9edcc87a7bb5b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFvdHVidXNpbiIsImlkIjoiNjhmNjMzZTQ4MTRkNjFhOTliMDU1NDY2IiwiaWF0IjoxNzYxMDYzMzEyLCJleHAiOjE3NjEwNjY5MTJ9.lr5xb58uM7rlLEQTq01oZNNlN3VyhEjR47lgvZDP5_8